# Generated by Django 3.2.4 on 2021-09-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setor_pessoal', '0004_remove_cadastro_funcionario_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_funcionario',
            name='cpf',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
