# Generated by Django 3.2.4 on 2021-08-23 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custo_Geral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(default=2021)),
                ('mes', models.IntegerField(choices=[(1, 'JANEIRO'), (2, 'FEVEREIRO'), (3, 'MARÇO'), (4, 'ABRIL'), (5, 'MAIO'), (6, 'JUNHO'), (7, 'JULHO'), (8, 'AGOSTO'), (9, 'SETEMBRO'), (10, 'OUTUBRO'), (11, 'NOVEMBRO'), (12, 'DEZEMBRO')])),
                ('producao_m2', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item_de_Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_de_producao', models.CharField(default='indefinido', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Custo_Geral_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(default=0)),
                ('valor', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('custo_geral_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custos_gerais.custo_geral')),
                ('item_de_producao_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='custos_gerais.item_de_producao')),
                ('unidade', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='producao.unidade')),
            ],
        ),
    ]
