# Generated by Django 3.2.4 on 2021-08-24 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producao', '0026_alter_resinamento_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abrasivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grao', models.IntegerField(default=0)),
                ('descricao', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.pessoa')),
                ('usuario_cadastrou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Abrasivos',
            },
        ),
        migrations.CreateModel(
            name='Parada_Politriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_final', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.TextField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualidade_Polimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Polimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('turno', models.PositiveIntegerField(default=1)),
                ('horimetro_inicial', models.PositiveBigIntegerField(default=0)),
                ('horimetro_final', models.PositiveBigIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.operador')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='Jogo_de_abrasivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grao', models.IntegerField(default=0)),
                ('descricao', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('DIAMANTADO', 'DIAMANTADO'), ('COMUM', 'COMUM')], default='COMUM', max_length=50)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('abr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polimento.abrasivo')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.pessoa')),
            ],
            options={
                'verbose_name_plural': 'Jogos de Abrasivos',
            },
        ),
        migrations.CreateModel(
            name='Chapas_Polidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('chapas_quebradas', models.PositiveIntegerField(default=0)),
                ('chapas_trincadas', models.PositiveIntegerField(default=0)),
                ('velocidade', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.bloco')),
                ('polimento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polimento.polimento')),
                ('qualidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polimento.qualidade_polimento')),
            ],
        ),
    ]
