# Generated by Django 3.2.4 on 2021-08-24 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapas_polidas',
            name='frequencia',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='parada_politriz',
            name='polimento_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='polimento.polimento'),
        ),
        migrations.AlterField(
            model_name='chapas_polidas',
            name='polimento_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polimento.polimento'),
        ),
    ]
