# Generated by Django 3.2.4 on 2021-08-24 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polimento', '0002_auto_20210824_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Polimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_polimento', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='parada_politriz',
            name='polimento_id',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.PROTECT, to='polimento.polimento'),
        ),
        migrations.AddField(
            model_name='chapas_polidas',
            name='tipo_polimento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='polimento.tipo_polimento'),
        ),
    ]
