# Generated by Django 3.2.4 on 2021-08-31 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polimento', '0004_auto_20210831_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abrasivo',
            options={},
        ),
        migrations.RemoveField(
            model_name='abrasivo',
            name='fornecedor',
        ),
    ]
