# Generated by Django 3.2.4 on 2021-08-31 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0034_alter_resinamento_data'),
        ('polimento', '0005_auto_20210831_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='abrasivo',
            name='fornecedor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='producao.pessoa'),
        ),
    ]
