# Generated by Django 3.2.4 on 2021-09-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polimento', '0006_abrasivo_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polimento',
            name='horimetro_final',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='polimento',
            name='horimetro_inicial',
            field=models.FloatField(default=0),
        ),
    ]
