# Generated by Django 3.2.4 on 2021-09-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polimento', '0007_auto_20210901_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo_de_abrasivos',
            name='data',
        ),
        migrations.AlterField(
            model_name='jogo_de_abrasivos',
            name='quantidade',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
