# Generated by Django 3.2.4 on 2021-08-23 12:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0019_alter_resinamento_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='resinamento',
            name='bloco',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='producao.bloco'),
        ),
        migrations.AlterField(
            model_name='resinamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 8, 23, 12, 22, 12, 370252, tzinfo=utc)),
        ),
    ]
