# Generated by Django 3.2.4 on 2021-08-23 12:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0022_auto_20210823_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resinamento',
            name='observacao',
        ),
        migrations.AlterField(
            model_name='resinamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 8, 23, 12, 28, 1, 857810, tzinfo=utc)),
        ),
    ]
