# Generated by Django 3.2.4 on 2021-08-23 12:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0023_auto_20210823_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='resinamento',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resinamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 8, 23, 12, 31, 21, 419755, tzinfo=utc)),
        ),
    ]
