# Generated by Django 3.2.4 on 2021-08-24 18:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0025_auto_20210823_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resinamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 8, 24, 18, 11, 30, 34635, tzinfo=utc)),
        ),
    ]
