# Generated by Django 3.2.4 on 2021-08-25 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0028_alter_resinamento_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='resina',
            name='dados_tecnicos',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resinamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 8, 25, 17, 30, 43, 910982, tzinfo=utc)),
        ),
    ]
