# Generated by Django 3.2.4 on 2021-09-01 16:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0035_alter_resinamento_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resinamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 9, 1, 16, 16, 11, 871033, tzinfo=utc)),
        ),
    ]
