# Generated by Django 3.2.4 on 2021-09-06 18:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0036_alter_resinamento_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faturamento_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('mes_desc', models.CharField(max_length=100)),
                ('valor_interno', models.FloatField(default=0)),
                ('valor_externo', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'faturamento_view',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='resinamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 9, 6, 18, 20, 48, 925570, tzinfo=utc)),
        ),
    ]
