# Generated by Django 3.2.4 on 2021-09-06 18:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0037_auto_20210906_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resinamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 9, 6, 18, 26, 32, 654969, tzinfo=utc)),
        ),
    ]
