# Generated by Django 3.2.4 on 2021-09-09 14:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0040_auto_20210909_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_venda_item',
            name='altura_espessura',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Alt/Esp'),
        ),
        migrations.AlterField(
            model_name='pedido_venda_item',
            name='comprimento',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido_venda_item',
            name='identificacao',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pedido_venda_item',
            name='largura',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido_venda_item',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='pedido_venda_item',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='pedido_venda_item',
            name='valor',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='resinamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 9, 9, 14, 14, 1, 709316, tzinfo=utc)),
        ),
    ]
