# Generated by Django 3.2.4 on 2021-09-09 17:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0041_auto_20210909_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido_venda_item',
            name='identificacao',
        ),
        migrations.AlterField(
            model_name='pedido_venda_item',
            name='percentual_ipi',
            field=models.DecimalField(decimal_places=3, default=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='resinamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 9, 9, 17, 3, 50, 419260, tzinfo=utc)),
        ),
    ]
