# Generated by Django 3.2.4 on 2021-09-09 17:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0042_auto_20210909_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Un',
            fields=[
                ('unidade', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fator', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('descricao_unidade', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido_venda_item',
            name='unidade',
        ),
        migrations.AlterField(
            model_name='resinamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 9, 9, 17, 17, 19, 561993, tzinfo=utc)),
        ),
    ]
