# Generated by Django 3.2.4 on 2021-09-09 17:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0043_auto_20210909_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_venda_item',
            name='un',
            field=models.ForeignKey(default='M2', on_delete=django.db.models.deletion.PROTECT, to='producao.un'),
        ),
        migrations.AlterField(
            model_name='resinamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 9, 9, 17, 21, 23, 360048, tzinfo=utc)),
        ),
    ]
