# Generated by Django 3.2.4 on 2021-09-14 17:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0044_auto_20210909_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resinamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 9, 14, 17, 35, 27, 449587, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='LigaFatorConversao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dureza', models.IntegerField()),
                ('fator', models.FloatField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.liga')),
            ],
        ),
    ]
