# Generated by Django 3.2.4 on 2021-09-20 17:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0045_auto_20210914_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resinamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 9, 20, 17, 59, 39, 872254, tzinfo=utc)),
        ),
    ]
