# Generated by Django 3.2.4 on 2021-10-06 13:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0055_alter_resinamento_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resinamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 10, 6, 13, 27, 8, 53927, tzinfo=utc)),
        ),
    ]
