# Generated by Django 3.2.4 on 2021-10-06 17:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0056_alter_resinamento_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resinamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 10, 6, 17, 33, 57, 29660, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Resina_Valor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('data_compra', models.DateField(default=datetime.datetime(2021, 10, 6, 17, 33, 57, 28661, tzinfo=utc))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('resina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.resina')),
                ('un', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.un')),
            ],
        ),
    ]
