# Generated by Django 3.2.4 on 2021-10-14 19:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0057_auto_20211006_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resina_valor',
            name='data_compra',
            field=models.DateField(default=datetime.datetime(2021, 10, 14, 19, 12, 38, 198804, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resinamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 10, 14, 19, 12, 38, 199803, tzinfo=utc)),
        ),
    ]
