# Generated by Django 3.2.4 on 2021-10-15 13:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producao', '0061_auto_20211015_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao_pedreira',
            name='usuario',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resina_valor',
            name='data_compra',
            field=models.DateField(default=datetime.datetime(2021, 10, 15, 13, 59, 11, 526489, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resinamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 10, 15, 13, 59, 11, 526489, tzinfo=utc)),
        ),
    ]
